export const BASE_URL = 'http://localhost:3000'

export const IMAGE_URL = process.env.NEXT_PUBLIC_IMAGE_URL

export const Routes = {
  login: '/login',
  register: '/register',
  resetPassword: '/reset-password',
  error: '/404',
  homepage: '/',
  products: '/products',
  manageOrders: '/manage-orders',
  manageOrdersDetail: '/manage-orders/',
  productsDetail: '/products/',
  intro: '/intro',
  cart: '/cart',
  payment: '/payment',
  userInfo: '/user-info',
  man: '/man',
  woman: '/woman',
  baby: '/baby',
  accessory: '/accessory',
  support: '/support',
  admin: {
    homepage: '/admin',
    branch: '/admin/branch',
    branchDetail: '/admin/branch/detail',
    statistic: '/admin/statistic',
    staff: '/admin/staff',
    staffDetail: '/admin/staff/detail',
    staffRequest: '/admin/staff/request',
    account: '/admin/account',
    accountDetail: '/admin/account/detail',
    event: '/admin/event',
    eventDetail: '/admin/event/detail',
    goods: '/admin/goods',
    goodsDetail: '/admin/goods/detail',
    goodsTranfer: '/admin/goods/tranfer',
    warehouse: '/admin/warehouse',
    order: '/admin/order',
    orderDetail: '/admin/order/detail',
    orderOnline: '/admin/order/online',
  },
  branchManager: {
    homepage: '/branch-manager',
    branch: '/branch-manager/branch',
    branchDetail: '/branch-manager/branch/detail',
    statistic: '/branch-manager/statistic',
    staff: '/branch-manager/staff',
    staffDetail: '/branch-manager/staff/detail',
    staffRequest: '/branch-manager/staff/request',
    order: '/branch-manager/order',
    orderDetail: '/branch-manager/order/detail',
  },
  branchLeader: {
    homepage: '/branch-leader',
    staff: '/branch-leader/staff',
    staffDetail: '/branch-leader/staff/detail',
    statistic: '/branch-leader/statistic',
    order: '/branch-leader/order',
    orderDetail: '/branch-leader/order/detail',
  },
}
